version: '3'
services:
  core:
    build: .
    image: topazdb/core
    ports: 
      - "80:8081"

  db:
    image: topazdb/server

  api:
    image: topazdb/api
    environment:
      - TOPAZ_HOST=db
      - TOPAZ_USER=root
      - TOPAZ_PASSWORD=root
      - TOPAZ_DATABASE=topazdb