version: '3'
services:
  core:
    build: .
    image: topazdb/core  
    ports:
      - "80:80"
  
  gui:
    image: topazdb/gui
    ports:
      - "8080:8080"
  
  db:
    image: topazdb/server
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=${TOPAZ_DATABASE}
      - MARIADB_ROOT_PASSWORD=${TOPAZ_PASSWORD}

  api:
    image: topazdb/api
    environment:
      - TOPAZ_HOST=db
      - TOPAZ_USER
      - TOPAZ_PASSWORD
      - TOPAZ_DATABASE
