version: '3'
services:
  core:
    build: .
    image: topazdb/core  
    ports:
      - "80:80"
  
  gui:
    build: ./gui
    volumes:
      - ./gui:/var/topazdb-gui/
    command: npm start -- --watch
  
  db:
    build: ./server
    environment:
      - MARIADB_DATABASE=${TOPAZ_DATABASE}
      - MARIADB_ROOT_PASSWORD=${TOPAZ_PASSWORD}

  api:
    build: ./api
    environment:
      - TOPAZ_HOST=db
      - TOPAZ_USER
      - TOPAZ_PASSWORD
      - TOPAZ_DATABASE
